spring:
  application:
    name: fd-shop

  datasource:
    url: jdbc:postgresql://localhost:5432/fdshop
    username: postgres
    password: PedroSQL

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
